package expo.modules.zechinuscrypto

import android.util.Base64
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

// sdk = [34]: see the matching comment in CryptoKeyRefTest.kt.
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class InteropVectorTest {
  // Generated by `scripts/generate-interop-test-vectors.mjs` from the JS reference
  // implementation (@noble/ciphers, @noble/hashes) — same values as InteropVectorTests.swift.
  private val keyB64 = "CX9/TFHlhJ1lGSikGHI8DR3JmdZfsVf9q3a4hGxiBM8="
  private val nonceB64 = "UEN9EimZBgcXMACS"
  private val aadB64 = "WyJ1c2VyLTEiLCJ0YWJsZSIsImZpZWxkIiwicm93LTEiXQ=="
  private val plaintextB64 = "aW50ZXJvcCB0ZXN0IHBheWxvYWQg4oCUIERFSyBpc29sYXRpb24gdmVjdG9ycw=="
  private val expectedCiphertextB64 = "8dQ8/peXK0XRjZPishjA/CABh4vabVdYMGFxGnvcIgkFASD+MXAIwWIrlMz2bPzoDnA2F0jXCxHBRWKrSQc="
  private val hkdfSaltB64 = "DmyOFNEgPwgqMVW60PIi+w=="
  private val hkdfInfo = "zechinus/content-hash-v1"
  private val expectedHkdfB64 = "EjucCoq/C6sol+MQU/KgGhtaxpa7sfC6wuKfeYU9OL4="
  private val hmacPayloadB64 = "eyJhIjoxLCJiIjoidGVzdCJ9"
  private val expectedHmacHex = "82df75081a6723392b2de32d09ab6beeee0994d767223c8a95865d8805f246ec"

  private fun b64(s: String): ByteArray = Base64.decode(s, Base64.NO_WRAP)
  private fun key(): CryptoKeyRef = CryptoKeyRef(b64(keyB64))

  @Test
  fun decryptsJSGeneratedCiphertext() {
    val decrypted = key().aesGcmDecrypt(b64(nonceB64), b64(aadB64), b64(expectedCiphertextB64))
    assertEquals(plaintextB64, Base64.encodeToString(decrypted, Base64.NO_WRAP))
  }

  @Test
  fun encryptProducesTheSameCiphertextAsJS() {
    val ct = key().aesGcmEncrypt(b64(nonceB64), b64(aadB64), b64(plaintextB64))
    assertEquals(expectedCiphertextB64, Base64.encodeToString(ct, Base64.NO_WRAP))
  }

  @Test
  fun hkdfMatchesJS() {
    val derived = key().hkdfDerive(b64(hkdfSaltB64), hkdfInfo, 32)
    assertEquals(expectedHkdfB64, Base64.encodeToString(derived, Base64.NO_WRAP))
  }

  @Test
  fun hmacMatchesJS() {
    val k = key()
    k.initMacKey(b64(expectedHkdfB64)) // the MAC key IS the HKDF output, as in createKeyHandle
    assertEquals(expectedHmacHex, k.hmacSha256(b64(hmacPayloadB64)))
  }
}
