import XCTest
@testable import ExpoZechinusCrypto

final class InteropVectorTests: XCTestCase {
  // Generated by `scripts/generate-interop-test-vectors.mjs` from the JS reference
  // implementation (@noble/ciphers, @noble/hashes) — see that script for how these
  // relate to each other.
  let keyB64 = "CX9/TFHlhJ1lGSikGHI8DR3JmdZfsVf9q3a4hGxiBM8="
  let nonceB64 = "UEN9EimZBgcXMACS"
  let aadB64 = "WyJ1c2VyLTEiLCJ0YWJsZSIsImZpZWxkIiwicm93LTEiXQ=="
  let plaintextB64 = "aW50ZXJvcCB0ZXN0IHBheWxvYWQg4oCUIERFSyBpc29sYXRpb24gdmVjdG9ycw=="
  let expectedCiphertextB64 = "8dQ8/peXK0XRjZPishjA/CABh4vabVdYMGFxGnvcIgkFASD+MXAIwWIrlMz2bPzoDnA2F0jXCxHBRWKrSQc="
  let hkdfSaltB64 = "DmyOFNEgPwgqMVW60PIi+w=="
  let hkdfInfo = "zechinus/content-hash-v1"
  let expectedHkdfB64 = "EjucCoq/C6sol+MQU/KgGhtaxpa7sfC6wuKfeYU9OL4="
  let hmacPayloadB64 = "eyJhIjoxLCJiIjoidGVzdCJ9"
  let expectedHmacHex = "82df75081a6723392b2de32d09ab6beeee0994d767223c8a95865d8805f246ec"

  private func b64(_ s: String) -> Data { Data(base64Encoded: s)! }
  private func key() throws -> CryptoKeyRef { try CryptoKeyRef(rawBytes: b64(keyB64)) }

  func testDecryptsJSGeneratedCiphertext() throws {
    let decrypted = try key().aesGcmDecrypt(b64(nonceB64), b64(aadB64), b64(expectedCiphertextB64))
    XCTAssertEqual(decrypted.base64EncodedString(), plaintextB64)
  }

  func testEncryptProducesTheSameCiphertextAsJS() throws {
    let ct = try key().aesGcmEncrypt(b64(nonceB64), b64(aadB64), b64(plaintextB64))
    XCTAssertEqual(ct.base64EncodedString(), expectedCiphertextB64)
  }

  func testHkdfMatchesJS() throws {
    let derived = try key().hkdfDerive(b64(hkdfSaltB64), hkdfInfo, 32)
    XCTAssertEqual(derived.base64EncodedString(), expectedHkdfB64)
  }

  func testHmacMatchesJS() throws {
    let k = try key()
    try k.initMacKey(b64(expectedHkdfB64)) // the MAC key IS the HKDF output, as in createKeyHandle
    XCTAssertEqual(try k.hmacSha256(b64(hmacPayloadB64)), expectedHmacHex)
  }
}
